rules = [
  DisableSyntax
  LeakingImplicitClassVal # ensure implicits are kept private
  NoValInForComprehension
  RedundantSyntax
]

DisableSyntax {
  noVars = true       # avoid mutable state
  noThrows = true     # use futures instead / handle gracefully-er
  noFinalVal = true   # val is final / immutable by default AFAIK
  noNulls = true      # use Option(...) instead
  noReturns = true    # last statement of function is returned by default
  noWhileLoops = true # better for immutability + performance
}


# Taken a bit more of a chill approach here, by default all
# of these are set to true. Made some false in case they 
# somehow break things by being auto-removed.
RemoveUnused {
  imports = false # imports will still be removed, see OrganizeImports.removeUnused
  privates = false
  locals = true
  patternvars = false
  params = false
}
