rules = [
  OrganizeImports
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RedundantSyntax,
  NoAutoTupling,
  ExplicitResultTypes
]

OrganizeImports {
  blankLines = Manual
  coalesceToWildcardImportThreshold = 5
  expandRelative = true
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = Merge
  groups = [
    "re:(javax?|scala)\\."
    "---"
    "*"
    "---"
    "uk.gov.hmrc."
    "---"
    "uk.gov.hmrc.app."
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = DEFAULT
  removeUnused = false
}

DisableSyntax {
  noReturns = true
  noWhileLoops = true
}


# Taken a bit more of a chill approach here, by default all
# of these are set to true. Made some false in case they 
# somehow break things by being auto-removed.
RemoveUnused {
  imports = false # imports will still be removed, see OrganizeImports.removeUnused
  privates = false
  locals = true
  patternvars = false
  params = false
}
